GET http://localhost:3000/bank-accounts

@bank_acount_id = 6e4635ce-88d1-4e58-9597-d13fc446ee47

###
GET http://localhost:3000/bank-accounts/{{bank_acount_id}}

###
POST http://localhost:3000/bank-accounts
Content-Type: application/json

{
    "account_number": "1111-1",
    "owner_name": "John Doe"
}


###
GET http://localhost:3000/bank-accounts/{{bank_acount_id}}/pix-keys

###
POST http://localhost:3000/bank-accounts/{{bank_acount_id}}/pix-keys
Content-Type: application/json

{
    "kind": "email",
    "key": "user10@email.com"
}