GET http://localhost:3000/bank-accounts

@bank_acount_id = 5c55ad3d-ed97-486a-be07-075ee24125d0

###
GET http://localhost:3000/bank-accounts/{{bank_acount_id}}

###
POST http://localhost:3000/bank-accounts
Content-Type: application/json

{
    "account_number": "1111-1",
    "owner_name": "John Doe"
}


###
GET http://localhost:3000/bank-accounts/{{bank_acount_id}}/pix-keys

###
POST http://localhost:3000/bank-accounts/{{bank_acount_id}}/pix-keys
Content-Type: application/json

{
    "kind": "email",
    "key": "user10@email.com"
}