services:
  app:
    build: .
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - .:/home/node/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  db:
    image: postgres:9.4
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nest
    volumes:
      - .docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
